export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  ORDER_NOT_UNIQUE = 'ORDER_NOT_UNIQUE',
  NOT_FOUND = 'NOT_FOUND',
  PREVIOUS_PHASE_NOT_COMPLETED = 'PREVIOUS_PHASE_NOT_COMPLETED',
  NEXT_PHASE_DONE = 'NEXT_PHASE_DONE'
}
